In [1]:
print("hello  world!")

hello  world!


In [6]:
# this is a ist in python
a = [1, 2, 3]
a.append(4)
b = a
print(b)

[1, 2, 3, 4]


In [7]:
#isinstance  check if the passed is among the type in the tuple
a = "kim"
isinstance(a, (int, float))

False

In [9]:
a = "foo"
print(a)

<built-in method capitalize of str object at 0x7f7a0f0ff450>
foo


In [10]:
def isit(obj):
    try:
        iter(obj)
        return True
    except TypeError:
        return False
    
isit("a string")

True

In [11]:
isit(5)

False

In [ ]:
# Dictionary list and arrays are mutable while tuples and strings re immutable
# you can convert a python object to a string using str


In [24]:
for i in range(4):
    print("*")
    print("Tuna separate hapa")
    for j in range(4):
        print( i, j)

*
Tuna separate hapa
0 0
0 1
0 2
0 3
*
Tuna separate hapa
1 0
1 1
1 2
1 3
*
Tuna separate hapa
2 0
2 1
2 2
2 3
*
Tuna separate hapa
3 0
3 1
3 2
3 3


In [19]:
#lets learnig dictionary
d1 = {"a": "some values", "b": [1,2,3]}
d1

{'a': 'some values', 'b': [1, 2, 3]}

In [7]:
#today we are going to learn about numpy pandas and maplotlip do some question and see how to apply on real world
#Numpy in full is numerical python

import numpy as np

data = np.array([[1.5, -0.1, 3], [0, -3, 6.5]])
#multiplies everything by 10
data * 10
#adds each elemt by itself
data + data
data.shape


(2, 3)

In [12]:
#creating ndarrays
data1 = [6,7.5, 8, 0, 1]

arr1 = np.array(data1)
arr1
data2 = [[1, 2, 3, 4],[5, 6, 7, 8]]
arr2 = np.array(data2)
arr2
arr2.dtype

dtype('int64')

In [14]:
#numpy.arrange
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [18]:
#basic indexing and slicing 
arr = np.arange(10)
arr


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [22]:
arr[5:8] = 12
    
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

In [24]:
arr2_d = np.array([[1,2,3], [4, 5, 6],[7, 8, 9,]])
arr2_d[2]

array([7, 8, 9])

In [27]:
arr2_d[0][2]
arr2_d[2,0]

np.int64(7)

In [28]:
arr2_d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [33]:
arr2_d[:, :1]

array([[1],
       [4],
       [7]])

In [35]:
#fancy indexing 
arr = np.zeros((8,4))
for i in range(8):
    arr[i] = i
arr

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

In [36]:
arr[[4, 3, 0, 6]]

array([[4., 4., 4., 4.],
       [3., 3., 3., 3.],
       [0., 0., 0., 0.],
       [6., 6., 6., 6.]])

In [39]:
#Transposign arrays and swapping axes
arr = np.arange(15).reshape((3,5))
# the function T is used for swapping 
arr.T

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [40]:
arr = np.array([[0, 1, 0], [1, 2, -2], [6, 3, 2], [-1, 0, -1], [1, 0, 1
]])
arr

array([[ 0,  1,  0],
       [ 1,  2, -2],
       [ 6,  3,  2],
       [-1,  0, -1],
       [ 1,  0,  1]])

In [41]:
np.dot(arr.T, arr)

array([[39, 20, 12],
       [20, 14,  2],
       [12,  2, 10]])

In [43]:
#pseudorandom number genration

samples = np.random.standard_normal(size=(4,4))
samples


array([[-2.4255741 , -0.54011508,  0.674112  ,  0.06392137],
       [ 0.88255461, -1.19118529, -1.23098645, -0.15810138],
       [-1.02164633,  0.05769377, -0.01006232,  1.49648506],
       [-2.65039875, -0.13266504, -1.10090935,  0.71489618]])

In [54]:
import numpy as np
rng = np.random.default_rng(seed=1234)
x = rng.standard_normal(8)
x


array([-1.60383681,  0.06409991,  0.7408913 ,  0.15261919,  0.86374389,
        2.91309922, -1.47882336,  0.94547297])

In [51]:
y = rng.standard_normal(8)

array([-1.66613546,  0.34374458, -0.51244371,  1.32375896, -0.86028019,
        0.5194932 , -1.26514372, -2.15913901])

In [ ]:
np.maximum(x,y)

In [ ]:
#pandas
import pandas as pd
df = pd.read_csv('Airbnb_Open_Data.csv')

df.head(10)
